"""added username

Revision ID: 333a3065fdda
Revises: 6538e1dba139
Create Date: 2023-10-01 11:15:55.087830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333a3065fdda'
down_revision = '6538e1dba139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
